### ISSUE TITLE
Generate K8ssandraCluster spec to match test input model

### ISSUE THREAD

**Issue by jeffbanks** [k8ssandra/cloud-readiness#15]
Automation for test precondition setup to populate the K8ssandraCluster specification used in a cloud-readiness test with references to unique names as defined by the test input model.

Request: The cloud-readiness framework will generate a unique K8ssandra cluster name and full context name(s) based on the number of clusters provisioned.

**Example**

Cluster name: 
- bootz-k8c-cluster

Contexts: 
-  gke_community-ecosystem_us-central1_dev-bootz1
-  gke_community-ecosystem_us-central1_dev-bootz2
-  gke_community-ecosystem_us-central1_dev-bootz3

Load and populate the `K8ssandraCluster` specification used in the install to include those names.

File reference: K8ssandra -> test -> config -> k8ssandra-clusters.yaml

```yaml
metadata:
  name: bootz-k8c-cluster
...
spec:
  cassandra:
    datacenters:
      - metadata:
          name: dc1
        k8sContext: gke_community-ecosystem_us-central1_dev-bootz1
        size: 3
        stargate:
          size: 1
          heapSize: 256M
      - metadata:
          name: dc2
        k8sContext: gke_community-ecosystem_us-central1_dev-bootz2
        size: 3
        stargate:
          size: 1
          heapSize: 256M
      - metadata:
          name: dc3
        k8sContext: gke_community-ecosystem_us-central1_dev-bootz3
        size: 3
        stargate:
          size: 1
          heapSize: 256M
```
